#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_message:
    <<: &mib_message
      # Building the image
      image: "mib-message:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "5003:5003"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
      - FLASK_ENV=production
    depends_on:
      - db
      - migrations
      - redis

  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_message
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure

  redis_message:
    container_name: redis_message
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6380"

  celery_worker_message:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -b "redis://redis:6380" -A wsgi.celery_app worker --loglevel=info
    links:
      - redis_message
    depends_on:
      - redis_message

  celery_beat_message:
    build:
      context: .
    command: celery -b "redis://redis:6380" -A wsgi.celery_app beat --loglevel=info
    depends_on:
      - redis_message


# Declaring all volumes
volumes:
  pgdata: # for maintaing db data
