"""empty message

Revision ID: 124a8d5f7051
Revises: 
Create Date: 2021-11-12 13:38:18.031320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.schema import PrimaryKeyConstraint


# revision identifiers, used by Alembic.
revision = '124a8d5f7051'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer, nullable=False),
    sa.Column('receiver_id', sa.Integer, nullable=False),
    sa.Column('delivery_date', sa.Date),
    sa.Column('creation_date', sa.Date),
    sa.Column('body', sa.Unicode(128), nullable=False),
    sa.Column('image', sa.Unicode(1000000), nullable=False),
    sa.Column('is_delivered', sa.Boolean, nullable=False),
    sa.Column('is_draft', sa.Boolean, nullable=True),
    sa.Column('opened', sa.Boolean, nullable=True),
    sa.Column('is_opened_notified', sa.Boolean, nullable=True),
    sa.Column('deleted', sa.Boolean, nullable=True),
    sa.Column('sender_nickname', sa.Unicode(length=128), nullable= True),
    sa.Column('receiver_nickname', sa.Unicode(length=128), nullable = True),
    sa.PrimaryKeyConstraint('message_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Message')
    # ### end Alembic commands ###
